# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:

jobs:
  publish:
    strategy:
      matrix:
        options:
          - ''
          - '-p:RepositoryUrl=https://github.com/${{ github.repository }}'
          - '-p:RepositoryUrl=https://github.com/${{ github.repository_owner }}/unknown_repo'
          - '-p:RepositoryUrl=https://github.com/github/github'
      fail-fast: false

    runs-on: ubuntu-latest

    # Use example from https://github.com/actions/setup-dotnet
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use.
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Create the package ${{ matrix.options }}
      run: dotnet pack --configuration Release -p:Version=0.0.0-g${{ github.sha }} ${{ matrix.options }}

    - name: Publish the package to GPR
      run: dotnet nuget push bin/Release/*.nupkg
