# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:

jobs:
  public:
    runs-on: ubuntu-latest

    # Use example from https://github.com/actions/setup-dotnet
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use.
        source-url: https://nuget.pkg.github.com/${{ github.repository }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Create the package
      run: dotnet pack --configuration Release

    - name: Publish the package to GPR
      run: dotnet nuget push bin/Release/*.nupkg
